freebsd_task:
    freebsd_instance:
        image_family: freebsd-12-2
    gmake_script: pkg install -y gmake
    matrix:
        - name: freebsd_clang
          env:
              CXX: clang++
        - name: freebsd_gcc
          gcc_script: pkg install -y gcc
          env:
              CXX: g++
    test_script: gmake -j4 test
    env:
        LC_ALL: en_US.UTF-8

linux_task:
    locales_script:
        - apt-get update && apt-get -y install locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8
    matrix:
        - name: linux_clang
          container:
              image: silkeh/clang:6
          clang_script:
              - apt-get -y install pkg-config libncursesw5-dev
          env:
              CXX: clang++
        - name: linux_gcc
          container:
              image: gcc:7
    test_script: make -j4 test
    env:
        LC_ALL: en_US.UTF-8

macos_task:
    osx_instance:
        image: mojave-base
    matrix:
        - name: macos_clang
          env:
              CXX: clang++
        - name: macos_gcc
          gcc_script: brew install gcc@7
          env:
              CXX: g++-7
    test_script: make -j4 test
