freebsd_task:
    freebsd_instance:
        image_family: freebsd-13-0
    gmake_script: pkg install -y gmake
    matrix:
        - name: freebsd_clang
          env:
              CXX: clang++
        - name: freebsd_gcc
          gcc_script: pkg install -y gcc
          env:
              CXX: g++
    test_script: gmake -j4 test
    env:
        LC_ALL: en_US.UTF-8

linux_task:
    locales_script:
        - apt-get update && apt-get -y install locales
        - echo "en_US.UTF-8 UTF-8" >> /etc/locale.gen
        - locale-gen en_US.UTF-8
    matrix:
        - name: linux_clang
          container:
              image: silkeh/clang:10
          env:
              CXX: clang++
        - name: linux_gcc
          container:
              image: gcc:10
    test_script: make -j4 test
    env:
        LC_ALL: en_US.UTF-8

macos_task:
    osx_instance:
        image: big-sur-base
    matrix:
        - name: macos_clang
          clang_script: brew install llvm@11
          env:
              CXX: /usr/local/opt/llvm@11/bin/clang++
        - name: macos_gcc
          gcc_script: brew install gcc@10
          env:
              CXX: g++-10
    test_script: make -j4 test
