name: Question
description: Couldn't find an answer in the documentation? Ask away!
labels: question
title: "[QUESTION] "
body:

    - type: markdown
      attributes:
        value: |
            Please make sure to [search issues](https://github.com/mawww/kakoune/issues?q=is%3Aissue) before creating a new one, to avoid duplicates and centralise conversations.

            If you need to have a question about the editor itself (options, behaviour, code…) answered, make sure to check the [documentation](https://github.com/mawww/kakoune/tree/master/doc/pages) (also available via the `doc` command in the editor) or drop by [IRC](https://web.libera.chat/?channels=#kakoune) to get instant feedback.

    - type: textarea
      attributes:
          label: "Question"
          description: "Couldn't find an answer in the documentation? Ask away!"
      validations:
        required: true
