KAKOUNE(1)
==========

NAME
----
registers - a

Description
-----------
Registers are named lists of text -instead of simply text- in order to interact
well with multiselection.  They are used for various purposes, like storing
the last yanked test, or the captured groups associated with the selections.

Interacting
-----------
*<c-r><c>*::
	when in insert mode or in a prompt, insert the value stored in the
	*c* register (single character)

*"<c>*::
	in normal mode, select the *<c>* register (single character)

Default registers
-----------------
Most commands using a register default to a specific one if not specified:

*"*::
	default yank, used by yanking and pasting commands like *y*, *p*
	and *R*

*/*::
	default search register, used by regex based commands like *s*, *\**
	or */*

*@*::
	default macro register, used by *q* and *Q*

*^*::
	default mark register, used by *z* and *Z*

Special registers
-----------------
Some registers are not general purposes, they cannot be written to, but they
contain some special data

*%*::
	current buffer name

*.*::
	current selection contents

*#*::
	selection indices (first selection has 1, second has 2, ...)
