= Changelog

This changelog contains major and/or breaking changes to Kakoune between
released versions.

== Development version

This version contains a significant overhaul of various Kakoune
features that can break user configuration. This was a necessary
change to make Kakoune command model cleaner and more robust.

* `%sh{...}` strings are not reparsed automatically anymore, they need
  to go through an explicit `evaluate-commands`

* The `-allow-override` switch from `define-command` has been renamed
  `-override`.

* The search prompt uses buffer word completion so that fuzzy completion
  can be used to quickly search for a buffer word.

* The `wrap` highlighter can accept a new `-marker <marker_text>` switch.

* The command line syntax has changed to support robust escaping, see
  <<command-parsing#,`:doc command-parsing`>>.

* Various lists (options, registers...) in Kakoune are now written using
  the command line syntax:

  - `set-register` now take an arbitrary number of parameters and sets
    the register to multiple strings. `%reg` expands to a list of strings.

  - `%opt` expands list options as list of strings.

  - selection descs are whitespaces separated instead of `:` separated

* Highlighters syntax has changed to permit explicit naming and remove
  highlighter specific name parameters (such as for the group highlighter)
  `add-highlighter <path>/<name> <type> <params>` is the new syntax.

* Regions highlighters have been overhauled and are now specified with
  a sequence of commands instead of a single one:

  ------------------------------------------------------------------
  add-highlighter <path>/<name> regions
  add-highlighter <path>/<name>/<region name> region <begin> <end> \
  <recurse> <type> <params>
  ------------------------------------------------------------------

  They also are not necessarily groups anymore, a region can directly
  apply any other highlighter

  See <<highlighters#,`:doc highlighters`>>

== Kakoune 2018.04.13

First official Kakoune release.
