= Execute-keys and Evaluate-commands

== Description

The *execute-keys* and *evaluate-commands* commands can be used to run
Kakoune commands:

--------------------------------------------
execute-keys [<switches>] <key> ...
evaluate-commands [<switches>] <command> ...
--------------------------------------------

*execute-keys* runs keys as if they were pressed, whereas *evaluate-commands*
evaluates its given parameters as if they were entered in the command prompt.
By default, their execution happens within the context of the current client,
and stops when the last key/command is reached, or an error is raised.

*execute-keys* also saves the following registers, who are then restored
when the commands have been executed: */*, *"*, *|*, *^*, *@*.

*evaluate-commands* does not save any registers by default
(see <<registers#,`:doc registers`>>).

== Optional switches

*-buffer* <names>::
    execute in the context of each buffer in the comma separated list
    *names*. `*` as a name can be used to iterate on all buffers.

*-client* <name>::
    execute in the context of client *name*.

*-try-client* <name>::
    execute in the context of client *name* if such client exists, or in
    the current context otherwise.

*-draft*::
    execute in a copy of the context of the selected client. Modifications
    to the selections or input state will not affect the client. This
    allows making modifications to the buffer without modifying the user’s
    selection.

*-itersel*::
    execute once per selection, in a context containing only the considered
    selection. This permits avoiding cases where the selections may get
    merged.

*-save-regs* <regs>::
    *regs* is a string of registers to be restored after execution (overwrites
    the list of registers saved by default, see <<description,Description>>).

== evaluate-commands specific switches

*-no-hooks*::
    disable hook execution while executing the keys/commands
    (see <<hooks#disabling-hooks,`:doc hooks`>>).

== execute-keys specific switches

*-with-hooks*::
    the execution of keys will trigger existing hooks
    (see <<hooks#,`:doc hooks`>>)

*-with-maps*::
    use user key mappings instead of built-in keys
    (see <<mapping#,`:doc mapping`>>).
