= Faces

== Declaration

A 'face' refers how the specified text is displayed, it has a foreground
color, a background color, and some attributes. The value of a face has the
following format:

--------------------------------
fg_color[,bg_color][+attributes]
--------------------------------

*fg_color*, *bg_color*::
    a color whose value can be one of the following:

        *black*, *blue*, *cyan*, *green*, *magenta*, *red*, *yellow*, *white*:::
            a named color

        *bright-black*, *bright-blue*, *bright-cyan*, *bright-green*, *bright-magenta*, *bright-red*, *bright-yellow*, *bright-white*:::
            the bright equivalent of the above default colors

        *default*:::
            keep the existing color

        *rgb:RRGGBB*:::
            RGB value encoded in hexadecimal

*attributes*::
    string whose individual letters set an attribute:

        *B*:::
            blink
        *b*:::
            bold
        *d*:::
            dim
        *e*:::
            exclusive, override previous faces instead of merging with them
        *i*:::
            italic
        *r*:::
            reverse
        *u*:::
            underline

== Builtin faces

The following default faces are used by color schemes to highlight certain
areas of the user interface:

*BufferPadding*::
    padding characters that follow the last line of a buffer

*Default*::
    default terminal foreground and background color

*Error*::
    error messages

*Information*::
    information windows and messages

*MenuBackground*::
    unselected elements in menus

*MenuForeground*::
    selected element in menus

*MenuInfo*::
    additional information of elements in menus

*PrimaryCursor*::
    cursor of the primary selection

*SecondaryCursor*::
    cursor of the secondary selection

*PrimaryCursorEol*::
    cursor of the primary selection when it lies on a newline character

*SecondaryCursorEol*::
    cursor of the secondary selection when it lies on a newline character

*PrimarySelection*::
    main selection, every selected character except the cursor

*SecondarySelection*::
    secondary selection, every selected character except the cursor

*Prompt*::
    prompt displayed on the status line

*StatusLine*::
    regular text on the status line

*StatusCursor*::
    status line cursor

*StatusLineInfo*::
    special information on the status line

*StatusLineMode*::
    current mode (except the normal mode) on the status line

*StatusLineValue*::
    special values (numeric prefixes, registers, etc.) on the status line

=== Builtin highlighters faces

The following faces are used by builtin highlighters when enabled
(see <<highlighters#,`:doc highlighters`>>):

*LineNumbers*::
    regular line number (`number-lines` highlighter)

*LineNumberCursor*::
    line number of the main selection (`number-lines` highlighter)

*LineNumbersWrapped*::
    line number of wrapped lines (`number-lines` highlighter)

*MatchingChar*::
    matching opening or closing delimiter to the character under the cursor
    (`show-matching` highlighter)

*Whitespace*::
    any whitespace character (`show-whitespaces` highlighter)
