= Keys

== Key Syntax

Usual keys are written using their ascii character, including capital
keys. Non printable keys use an alternate name, written between *<*
and *>*, such as *<esc>* or *<del>*. Modified keys are written between
*<* and *>* as well, with the modifier specified as either *c* for
Control, *a* for Alt, or *s* for Shift, followed by a *-* and the key (either
its name or ascii character), for example *<c-x>*, *<a-space>*, *<c-a-w>*.

In order to bind some keys to arbitrary ones, refer to <<mapping#,`:doc mapping`>>

== Insert mode

*<esc>*::
    leave insert mode

*<backspace>*::
    delete characters before cursors

*<del>*::
    delete characters under cursors

*<left>*, *<right>*, *<up>*, *<down>*::
    move the cursors in given direction

*<home>*::
    move cursors to line begin

*<end>*::
    move cursors to end of line

*<c-r>*::
    insert contents of the register given by next key

*<c-v>*::
    insert next keystroke directly into the buffer, without interpreting it

*<c-u>*::
    commit changes up to now as a single undo group

*<a-;>*::
    escape to normal mode for a single command

== Insert mode completion

The `completers` option controls automatic completion, which kicks in when
the value specified in the `idle_timeout` option is reached.

*<c-o>*::
    disable automatic completion for this insert session

*<c-n>*::
    select next completion candidate

*<c-p>*::
    select previous completion candidate

*<c-x>*::
    explicit insert completion query, followed by:

    *f*:::
        explicit file completion

    *w*:::
        explicit word completion (current buffer)

    *W*:::
        explicit word completion (all buffers)

    *l*:::
        explicit line completion (current buffer)

    *L*:::
        explicit line completion (all buffers)

== Using Counts

In normal mode, commands can be prefixed with a numeric count, which can control
the command behaviour.

For example, *3W* selects 3 consecutive words and *3w* select the third word on
the right of the end of each selection.

== Disabling Hooks

Any normal mode command can be prefixed with *\* which will disable hook execution
for the duration for the command (including the duration of modes the command could
move to, so *\i* will disable hooks for the whole insert session).

As autoindentation is implemented in terms of hooks, this can be used to disable
it when pasting text.

== Movement

'word' is a sequence of alphanumeric characters or underscore, and 'WORD'
is a sequence of non whitespace characters. Generally, a movement on it own
will move each selection to cover the text moved over, while holding down
the Shift modifier and moving will extend each selection instead.

*h*, *<left>*::
    select the character on the left of the end of each selection

*j*, *<down>*::
    select the character below the end of each selection

*k*, *<up>*::
    select the character above the end of each selection

*l*, *<right>*::
    select the character on the right of the end of each selection

*w*::
    select the word and following whitespaces on the right of the end of each selection

*b*::
    select preceding whitespaces and the word on the left of the end of each selection

*e*::
    select preceding whitespaces and the word on the right of the end of each selection

*<a-[wbe]>*::
    same as [wbe] but select WORD instead of word

*f*::
    select to the next occurrence of given character

*t*::
    select until the next occurrence of given character

*<a-[ft]>*::
    same as [ft] but in the other direction

*m*::
    select to matching character, see the `matching_pairs` option
    in <<options#,`:doc options`>>

*x*::
    select line on which the end of each selection lies (or next line when end lies
    on an end-of-line)

*<a-x>*::
    expand selections to contain full lines (including end-of-lines)

*<a-X>*::
    trim selections to only contain full lines (not including last
    end-of-line)

*%*::
    select whole buffer

*<a-h>*, *<home>*::
    select to line begin

*<a-l>*, *<end>*::
    select to line end

*/*::
    search (select next match)

*<a-/>*::
    search (select previous match)

*?*::
    search (extend to next match)

*<a-?>*::
    search (extend to previous match)

*n*::
    select next match

*N*::
    add a new selection with next match

*<a-n>*::
    select previous match

*<a-N>*::
    add a new selection with previous match

*pageup, <c-b>*::
    scroll one page up

*pagedown, <c-f>*::
    scroll one page down

*<c-u>*::
    scroll half a page up

*<c-d>*::
    scroll half a page down

*;*::
    reduce selections to their cursor

*<a-;>*::
    flip the direction of each selection

*<a-:>*::
    ensure selections are in forward direction (cursor after anchor)

*<a-.>*::
    repeat last object or *f*/*t* selection command

== Changes

*i*::
    enter insert mode before selections

*a*::
    enter insert mode after selections

*d*::
    yank and delete selections

*c*::
    yank and delete selections and enter insert mode

*.*::
    repeat last insert mode change (*i*, *a*, or *c*, including the
    inserted text)

*<a-d>*::
    delete selections (not yanking)

*<a-c>*::
    delete selections and enter insert mode (not yanking)

*I*::
    enter insert mode at the beginning of the lines containing
    the start of each selection

*A*::
    enter insert mode at the end of the lines containing
    the end of each selection

*o*::
    enter insert mode in a new line (or in a given count of new lines)
    below the end of each selection

*O*::
    enter insert mode in a new line (or in a given count of new lines)
    above the beginning of each selection

*<a-o>*::
    add an empty line below cursor

*<a-O>*::
    add an empty line above cursor

*y*::
    yank selections

*p*::
    paste after the end of each selection

*P*::
    paste before the beginning of each selection

*<a-p>*::
    paste all after the end of each selection, and select each pasted string

*<a-P>*::
    paste all before the start of each selection, and select each pasted string

*R*::
    replace selections with yanked text

*<a-R>*::
    replace selections with every yanked text

*r*::
    replace each character with the next entered one

*<a-j>*::
    join selected lines

*<a-J>*::
    join selected lines and select spaces inserted in place of line breaks

*<a-m>*::
    merge contiguous selections together (works across lines as well)

*>*::
    indent selected lines

*<a\->>*::
    indent selected lines, including empty lines

*<*::
    deindent selected lines

*<a-<>*::
    deindent selected lines, do not remove incomplete indent (3 leading
    spaces when indent is 4)

*|*::
    pipe each selection through the given external filter program and
    replace the selection with its output. Shell expansions are available,
    (See <<expansions#shell-expansions,`:doc expansions shell-expansions`>>)

*<a-|>*::
    pipe each selection through the given external filter program and
    ignore its output. Shell expansions are available,
    (See <<expansions#shell-expansions,`:doc expansions shell-expansions`>>)

*!*::
    insert command output before each selection. Shell expansions are available,
    (See <<expansions#shell-expansions,`:doc expansions shell-expansions`>>)

*<a-!>*::
    append command output after each selection. Shell expansions are available,
    (See <<expansions#shell-expansions,`:doc expansions shell-expansions`>>)

*u*::
    undo last change

*<a-u>*::
    move backward in history

*U*::
    redo last change

*<a-U>*::
    move forward in history

*&*::
    align selections, align the cursor of each selection by inserting spaces
    before the first character of each selection

*<a-&>*::
    copy indent, copy the indentation of the main selection (or the
    count one if a count is given) to all other ones

*`*::
    to lower case

*~*::
    to upper case

*<a-`>*::
    swap case

*@*::
    convert tabs to spaces in each selection, uses the buffer tabstop
    option or the count parameter for tabstop

*<a-@>*::
    convert spaces to tabs in each selection, uses the buffer tabstop
    option or the count parameter for tabstop

*_*::
    trim selections

*<a-)>*::
    rotate selections content, if specified, the count groups selections,
    so the following command

----------
    3<a-)>
----------

    rotate (1, 2, 3) and (3, 4, 6) independently

*<a-(>*::
    rotate selections content backward

== Goto commands

*g*, *G*::
    When a count is specified, *G* only extends the selection to the given line,
    *g* sends the anchor to the given line and a menu is then displayed which waits
    for one of the following additional keys:

    *h*:::
        go to line begin

    *l*:::
        go to line end

    *i*:::
        go to non blank line start

    *g*, *k*:::
        go to the first line

    *j*:::
        go to the last line

    *e*:::
        go to last char of last line

    *t*:::
        go to the first displayed line

    *c*:::
        go to the middle displayed line

    *b*:::
        go to the last displayed line

    *a*:::
        go to the previous (alternate) buffer

    *f*:::
        open the file whose name is selected

    *.*:::
        go to last buffer modification position

== View commands

*v*, *V*::
    *V* enters lock view mode (which will be left when the <esc> is hit),
    and *v* modifies the current view; a menu is then displayed which waits
    for one of the following additional keys:

    *v*, *c*:::
        center the main selection in the window (vertically)

    *m*:::
        center the main selection in the window (horizontally)

    *t*:::
        scroll to put the main selection on the top line of the window

    *b*:::
        scroll to put the main selection on the bottom line of the window

    *h*:::
        scroll the window count columns left

    *j*:::
        scroll the window count line downward

    *k*:::
        scroll the window count line upward

    *l*:::
        scroll the window count columns right

== Marks

Current selections position can be saved in a register and restored later on.
Marks use the *^* register by default (See <<registers#,`:doc registers`>>)

*Z*::
    save selections to the register

*z*::
    restore selections from the register

*<a-z>*, *<a-Z>*::
    *<a-z>* combines selections from the register with the current ones, whereas
    *<a-Z>* combines current selections with the ones in the register; a menu
    is then displayed which waits for one of the following additional keys:

    *a*:::
        append selections

    *u*:::
        keep a union of selections

    *i*:::
        keep an intersection of selections

    *<*:::
        select the selection with the leftmost cursor for each pair

    *>*:::
        select the selection with the rightmost cursor for each pair

    *+*:::
        select the longest selection

    *-*:::
        select the shortest selection

== Macros

Macros use the *@* register by default (See <<registers#,`:doc registers`>>)

*Q*::
    start or end macro recording

*q*::
    play a recorded macro

*<esc>*::
    end macro recording

== Searching

Searches use the */* register by default (See <<registers#,`:doc registers`>>)

***::
    set the search pattern to the main selection (automatically
    detects word boundaries)

*<a-***>*::
    set the search pattern to the main selection (verbatim, no smart
    detection)

== Jump list

Some commands, like the goto commands, buffer switch or search commands,
push the previous selections to the client's jump list. It is possible
to skim through the jump list using:

*<c-i>*::
    jump forward

*<c-o>*::
    jump backward

*<c-s>*::
    save selections

== Multiple selections

*s*::
    create a selection for each match of the given regex

*S*::
    split selections with the given regex

*<a-s>*::
    split selections on line boundaries

*<a-S>*::
    select first and last characters of each selection

*C*::
    copy the main selection to the next line

*<a-C>*::
    copy the main selection to the previous line

*<space>*::
    clear selections to only keep the main one

*<a-space>*::
    clear the main selection

*<a-k>*::
    keep selections that match the given regex

*<a-K>*::
    clear selections that match the given regex

*$*::
    pipe each selection to the given shell command and keep the ones
    for which the shell returned 0. Shell expansions are available,
    (See <<expansions#shell-expansions,`:doc expansions shell-expansions`>>)

*)*::
    rotate main selection (the main selection becomes the next one)

*(*::
    rotate main selection backward (the main selection becomes the previous one)

== Object Selection

For nestable objects, a count can be used in order to specify which surrounding
level to select.

*<a-a>*::
    select the whole object

*<a-i>*::
    select the inner object, that is the object excluding its surrounder.
    For example, for a quoted string, this will not select the quote, and
    for a word this will not select trailing spaces.

*[*::
    select to object start

*]*::
    select to object end

*{*::
    extend selections to object start

*}*::
    extend selections to object end

After these keys, a second key needs to be entered in order to specify
the wanted object:

*b*, *(*, *)*::
    select the enclosing parenthesis

*B*, *{*, *}*::
    select the enclosing {} block

*r*, *[*, *]*::
    select the enclosing [] block

*a*, *<*, *>*::
    select the enclosing <> block

*Q*, *"*::
    select the enclosing double quoted string

*q*, *'*::
    select the enclosing single quoted string

*g*, *`*::
    select the enclosing grave quoted string

*w*::
    select the whole word

*<a-w>*::
    select the whole WORD

*s*::
    select the sentence

*p*::
    select the paragraph

*␣*::
    select the whitespaces

*i*::
    select the current indentation block

*n*::
    select the number

*u*::
    select the argument

*c*::
    select user defined object, will prompt for open and close text

== Prompt commands

When pressing `:` in normal mode, Kakoune will open a prompt to enter a command.
The following keys are recognized by this mode to help edition.
(See <<commands#,`:doc commands`>>)

*<ret>*::
    validate prompt

*<esc>*::
    abandon without

*<left>*, *<a-h>*::
    move cursor to previous character

*<right>*, *<a-l>*::
    move cursor to next character

*<home>*::
    move cursor to first character

*<end>*::
    move cursor past the last character

*<backspace>*, *<a-x>*::
    erase character before cursor

*<del>*, *<a-d>*::
    erase character under cursor

*<c-w>*::
    advance to next word begin

*<c-a-w>*::
    advance to next WORD begin

*<c-b>*::
    go back to previous word begin

*<c-a-b>*::
    go back to previous WORD begin

*<c-e>*::
    advance to next word end

*<c-a-e>*::
    advance to next word end

*<up>*, *<c-p>*::
    select previous entry in history

*<down>*, *<c-n>*::
    select next entry in history

*<tab>*::
    select next completion candidate

*<s-tab>*::
    select previous completion candidate

*<c-r>*::
    insert then content of the register given by next key

*<c-v>*::
    insert next keystroke without interpreting it

*<c-f>*::
    insert the default value for this prompt

*<c-o>*::
    disable auto completion for this prompt

*<a-!>*::
    expand the typed expansions in currently entered text
    (See <<expansions#typed-expansions,`:doc expansions typed-expansions`>>)
