# define color scheme
#
# For Code
face value red
face type yellow
face identifier green
face string magenta
face error default,red
face keyword blue
face operator yellow
face attribute green
face comment cyan
face meta magenta

# For markup
face title blue
face header cyan
face bold red
face italic yellow
face mono green
face block magenta
face meta blue
face link cyan
face bullet cyan
face list yellow

def -shell-params runtime %{ %sh{
        while [ $# -gt 0 ]; do
            echo "source '${kak_runtime}/$1'"
            shift
        done
}}

%sh{
    if [ -n "${XDG_CONFIG_HOME}" ]; then
       localconfdir="${XDG_CONFIG_HOME}/kak"
    else
       localconfdir="$HOME/.config/kak"
    fi
    if [ -d "${localconfdir}/autoload" ]; then
        for rcfile in ${localconfdir}/autoload/*.kak; do
            echo "try %{ source '${rcfile}' } catch %{ }";
        done
    fi
    if [ -f "${localconfdir}/kakrc" ]; then
        echo "source '${localconfdir}/kakrc'"
    fi
}
