hook global WinCreate .* %{ addhl regex \h+(?=\n) 0:default,red }
hook global WinCreate .* %{ addhl number_lines }

%sh{ for rcfile in ${kak_runtime}/rc/*; do echo "try %{ source '${rcfile}' } catch %{ }"; done }
