name: Makefile CI
on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]
jobs:
  build:
    timeout-minutes: 10
    strategy:
      matrix:
        os: [ubuntu, macos]
        toolchain: [gcc, llvm]
        include:
          - os: ubuntu
            toolchain: gcc
            install_cmd: |
              sudo apt update
              sudo apt install g++
            CXX: g++
            make_args:
          - os: ubuntu
            toolchain: llvm
            install_cmd: |
              sudo apt update
              sudo apt install clang
            make_args: sanitize=address
            CXX: clang++
          - os: macos
            toolchain: gcc
            install_cmd: |
              brew update
              brew install gcc
            CXX: g++
            make_args:
          - os: macos
            toolchain: llvm
            install_cmd: |
              brew update
              brew install llvm
            CXX: clang++
            make_args:
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: ${{ matrix.install_cmd }}
    - name: Build and test
      run: make CXX=${{ matrix.CXX }} ${{ matrix.make_args }} -j$(nproc 2>/dev/null || sysctl -n hw.ncpu) test
