name: Makefile CI
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu, macos]
        toolchain: [gcc, llvm]
        include:
          - os: ubuntu
            toolchain: gcc
            install_cmd: |
              sudo apt update
              sudo apt install g++
            CXX: g++
          - os: ubuntu
            toolchain: llvm
            install_cmd: |
              sudo apt update
              sudo apt install clang
            CXX: clang++
          - os: macos
            toolchain: gcc
            install_cmd: |
              brew update
              brew install gcc
            CXX: g++
          - os: macos
            toolchain: llvm
            install_cmd: |
              brew update
              brew install llvm
            CXX: clang++
            
    runs-on: ${{ matrix.os }}-latest
    steps:
    - uses: actions/checkout@v3
    
    # TODO remove after https://github.com/actions/runner-images/issues/8659 is resolved
    - uses: mjp41/workaround8649@c8550b715ccdc17f89c8d5c28d7a48eeff9c94a8
      with:
        os: ${{ matrix.os }}-latest
        
    - name: Install dependencies
      run: ${{ matrix.install_cmd }}
    - name: Build and test
      run: make CXX=${{ matrix.CXX }} -j4 test
